# mdd completion                                           -*- shell-script -*-

# This bash completions script was generated by
# completely (https://github.com/dannyben/completely)
# Modifying it manually is not recommended

_mdd_completions_filter() {
  local words="$1"
  local cur=${COMP_WORDS[COMP_CWORD]}
  local result=()

  if [[ "${cur:0:1}" == "-" ]]; then
    echo "$words"
  
  else
    for word in $words; do
      [[ "${word:0:1}" != "-" ]] && result+=("$word")
    done

    echo "${result[*]}"

  fi
}

_mdd_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")
  local compline="${compwords[*]}"

  case "$compline" in
    'new'*)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_mdd_completions_filter "--folder --directory --dir --categories --cat --parent -c --tags --tag -t --series --group -g --date --publication --publish-at -d --summary --description --desc -s --template --tpl --headings --part --h2 --headings-level --hl --filename --draft --no-draft --publish --force --no-force --is-category --no-is-category --is-cat")" -- "$cur" )
      ;;

    *)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_mdd_completions_filter "new")" -- "$cur" )
      ;;

  esac
} &&
complete -F _mdd_completions mdd

# ex: filetype=sh
